export const TEMPLATE_HEADER_LINES: string[] = [
    "# Generated by env-example-gen",
    "# Copy this file to .env and replace placeholders with real values.",
];

export const DEFAULT_PLACEHOLDER = "<YOUR_VALUE_HERE>";
